server:
  port: 9999

spring:
  main:
    banner-mode: "console"
# 设置当前激活profile
  profiles:
    active: dev


# 文件上传配置 上传文件大小 请求文件大小
multipart:
  max-file-size: 1Mb
  max-request-size: 10Mb
  enabled: true

